---
title: "Planejamento e Controle da Produção"
subtitle: "Unidade 01 - Funções e planejamento e controle da produção"
author: "Renata Oliveira"
#subtitle: "Sejam bem vindos!"
footer:  "[Planejamento e Controle da Produção](https://adm-prod.github.io/site/)"
#logo: "images/logo.png"
title-slide-attributes: 
  data-background-size: contain
  data-background-color: '#5B888C'
format: 
  revealjs: 
    # confetti:
    #   particleCount: 150
    #   angle: 90
    #   spread: 360
    #   startVelocity: 25
    #   gravity: 0.65
    #   drift: 0
    #   ticks: 400
    #   colors: ["#0366fc", "#f54281", "#1fd14f"]
    #   scalar: 0.7
    embed-resources: false
    speaker_notes_style: minimal_style.css
    menu: true
    theme: 
      - dark
      - slides.scss
    incremental: true
    multiplex: true
    transition: fade
    slide-number: c/t
    width: 1600
    height: 900
    margin: 0.1
    echo: false
    overview: true
    touch: true
    keyboard: true
    controls-layout: bottom-right
    margin-left: 1em
    scrollable: true
    preview-links: auto
    chalkboard: true
    highlight-style: github
    code-fold: true
editor: source
execute:
  freeze: auto
filters:
  - style-speaker-note
  - reveal-auto-agenda
auto-agenda:
  #bullets: numbered
  #heading: Agenda
revealjs-plugins:
  - pointer
  - confetti
---

```{r, include=FALSE}
library(countdown)
```

## Agenda

::: {.nonincremental}
- Objetivos de aprendizagem 
- Função produção
- Fluxo de informações e materiais
- Divisão do horizonte de planejamento
- Objetivos de produção
- Classificação de sistemas produtivos
- Fluxos de informações e materiais
:::

## Objetivos de aprendizagem
Espera-se que ao final desta aula o aluno compreenda:   

::: {.midi}
- O conceito de função produção.  
- Objetivos da produção.  
- Divisão do horizonte de planejamento (longo prazo, médio prazo e curto prazo).  
- Fluxo de informações e materiais.  
- Diferentes tipos de leiaute (layout).  
- Tipos de sistema de produção: sistema contínuo, produção em massa, produção intermitente por lotes, produção por projeto.  
:::

---

::: {.huge}
Para que e a quem servem as organizações?
:::

`r countdown(minutes = 0, seconds = 42, left = 0, right = 0, padding = "50px", margin = "5%", font_size = "6em", play_sound = TRUE)`


## Função produção

::: {.poll}
**Função desenvolvimento de produto/serviço**   
Responsável por desenvolver novos produtos e serviços ou modificá-los
para gerar futuros pedidos dos clientes [Slack et al., 2009].   


**Função marketing (que inclui vendas)**   
Responsável por comunicar os produtos e serviços da organização a seus mercados para gerar pedidos de serviços e produtos dos clientes [Slack et al., 2009].
:::

## Função Produção

::: {.question}
**Função produção**    
Responsável pela criação e entrega de serviços e produtos com base nos pedidos do cliente [Slack et al., 2009].
:::

---

::: {.huge}
Qual a relação da Função Produção com a Engenharia de Materiais???
:::


## Fluxo de informações e materiais

## Divisão do horizonte de planejamento

## Objetivos de produção

## Classificação de sistemas produtivos

## Fluxos de informações e materiais

## Aquecimento

1. Escreva uma pergunta sobre seu entendimento preliminar de **ciência aberta** no ChatGPT.   
Exemplo: "Assuma que você é um pesquisador do CEFET_MG em campos das ciências sociais aplicadas. O que é Ciência Aberta?" 

2. Copie e cole no [Padlet](https://padlet.com/renataoliveira/ci-ncia-aberta-e-em-colabora-o-dhb0fd7faebyahdd) da disciplina. [Tempo](https://apps.garrickadenbuie.com/countdown/?_inputs_&time=%2220%3A00%22&update_every=%2210%22&warn_time=%225%3A00%22)

3. Vamos discutir

## Question


::: {.question}

teste

:::

## Perguntas e respostas

- O que é e por que fazer ciência em colaboração?
- Qual a diferença entre Ciência Aberta e 'ciência'?
- A Ciência Aberta excluí as Ciências Socias e Humanas?
- A Ciência Aberta conduz ao uso indevido ou incompreensão da investigação?
- A Ciência Aberta irá provocar uma sobrecarga de informação?

