---
title: Cinema Kinepolıs e Cinema UCI
---
Cinema Kinepolis em Bruxelas, Bélgica. 

O Kinepolis é considerado o maior complexo de cinemas do mundo, com 28 telas, um total de 8.000 lugares e quatro sessões de filmes todos os dias. Domina o mercado de cinemas na área, atraindo cerca de 60% do p´ublico frequentador de cinema. Uma das raz˜oes de seu sucesso ´e que est´a equipado com a mais recente tecnologia de proje¸c˜ao (telas grandes, som THX, Dolbi est´ereo, Som de Cinema Digital e Imax). Est´a localizado nos sub´urbios de Bruxelas, em Bruparck, pr´oximo do Est´adio Heizel e do famoso Atomium, a 15 minutos de carro ou de metrˆo. Apesar de a maioria dos consumidores ir de carro, h´a usualmente bastante lugar para estacionar, seja no estacionamento do pr´oprio cinema, seja nas instala¸c˜oes adjacentes do Bruparck.
Todas as sess˜oes s˜ao programadas para come¸car na mesma hora, todos os dias: `as 16h, `as 18h, `as 20h e `as 22h30. Já que a maioria dos espectadores chega cerca de 30 minutos antes do in´ıcio do filme, filas podem com freq¨uˆencia ser formadas nos
18 guichˆes de bilheteria, 10 no sagu˜ao principal e 8 na entrada secund´aria. Acima das bilheterias, h´a monitores de TV que
mostram o menu de filmes, a classifica¸c˜ao e a disponibilidade restante de lugares para cada um. O menu ocupa trˆes monitores!
Cada bilheteria tem um terminal de computador em rede e uma impressora de ingresso. Para cada consumidor, um c´odigo de
tela ´e inserido para identificar e confirmar a disponibilidade de lugar no filme requerido. Ent˜ao, o n´umero de lugares requeridos
´e alimentado e os ingressos s˜ao impressos, que, contudo, n˜ao alocam lugares marcados. O bilheteiro recebe ent˜ao o pagamento
em dinheiro ou cart˜ao de cr´edito e entrega o ingresso. Essa opera¸c˜ao toma em m´edia 19,5 segundos e s˜ao necess´arios mais
cinco segundos para que o consumidor seguinte mova-se para o guichˆe e o ciclo recomece. Dessa forma, a capacidade de pico
´e de aproximadamente 150 transa¸c˜oes por guichˆe por hora; 2.700 por hora, usando todos os guichˆes. Considerando que uma
transa¸c˜ao m´edia envolve a venda de aproximadamente 1,7 ingresso, o processo de venda pode satisfazer a uma entrada de 4.500
consumidores por hora, o que ´e suficiente para os n´ıveis normais de demanda; o tempo de fila raramente excede cinco minutos.
A capacidade de fornecer ingressos teria problemas se a demanda se aproximasse da capacidade total de lugares do centro.
Cinema UCI em Sol´ıhull, Birmingham O cinema UCI (United Cinemas International) existe desde 1989 e tem oito telas.
Foi constru´ıdo em um local privilegiado, um centro comercial, perto de uma movimentada rodovia, bem no centro da Inglaterra.
Quase todos os consumidores v˜ao de carro e v˜ao para o estacionamento privado do cinema, onde h´a, de maneira geral, espa¸co
suficiente; mas h´a, ocasionalmente, consider´avel congestionamento na entrada e sa´ıda antes do in´ıcio de filmes populares.
O cinema incorpora muitos recursos no “estado da arte”, que inclui o sistema de som THX de alta qualidade, sistema de
emiss˜ao de ingressos completamente computadorizado e v´ıdeo games fora, nas arcadas do sagu˜ao principal. H´a dois aparelhos
gigantes de TV na entrada do sagu˜ao, que informam atra¸c˜oes futuras. No total, as oito salas podem receber 1.840 pessoas;
a lota¸c˜ao das salas varia, e assim a gerˆencia do cinema pode alocar os filmes mais populares para as salas maiores e usar as
menores para exibi¸c˜oes menores.
Os t´ıtulos dos filmes s˜ao selecionados pela administra¸c˜ao central, mas a administra¸c˜ao local tem a responsabilidade pela
programa¸c˜ao das sess˜oes em cada sala. Os contratos com os distribuidores definem o n´umero de sess˜oes de cada dia, mas a
programa¸c˜ao detalhada est´a a cargo da gerˆencia do cinema. Os momentos de in´ıcio e fim dos oito filmes no UCI s˜ao separados
por intervalos de 10 minutos, com o filme mais popular em cada categoria (por exemplo, os somente para adultos), que come¸ca
antes. Devido aos filmes terem dura¸c˜oes diferentes e j´a que o gerente deve tentar maximizar a utiliza¸c˜ao dos lugares, a tarefa
de programa¸c˜ao ´e complexa e cr´ıtica para o desempenho financeiro da instala¸c˜ao.
O pessoal das bilheterias est´a continuamente alerta para a capacidade remanescente de cada sala nas telas de seus terminais.
H´a at´e quatro guichˆes de ingressos abertos por vez. O tempo meta por transa¸c˜ao completa ´e de 20 segundos, assim, o m´aximo
de venda ´e de 12 ingressos por minuto, ou 720 por hora. O n´umero m´edio de ingressos por transa¸c˜ao ´e 1,8, portanto, o m´aximo
n´umero de ingressos vendidos por hora ´e 1.300: tranquilamente dentro dos n´ıveis m´aximos de demanda esperada. Todos os
ingressos indicam posi¸c˜oes espec´ıficas de assento, e s˜ao alocados com base em primeiro-a-chegar-primeiro-servido. Uma central
de venda antecipada ´e agora oferecida pelo grupo UCI, em que os consumidores podem telefonar a um n´umero gratuito do Reino
Unido e encomendar seus ingressos, que ser˜ao retirados no cinema local, pagando com cart˜ao de cr´edito. Apesar de haver uma
pequena tarifa por esses servi¸cos, a vis˜ao ´e de que a conveniˆencia atrair´a mais usu´arios para compra de seus ingressos dessa
forma e, portanto, reduzir´a o n´umero de filas para pagar pelos ingressos na noite.
A declara¸c˜ao de miss˜ao do UCI enfatiza a necessidade de proporcionar instala¸c˜oes limpas e arrumadas, pessoal animado,
instala¸c˜oes de alimenta¸c˜ao adequadas e, acima de tudo, alta qualidade de exibi¸c˜ao de filmes e som. O UCI acredita que
proporciona a melhor experiˆencia em cinema fora de Londres.
Quest˜oes
1. Considerando os conceitos apresentados em sala de aula, apresente exemplos de recursos a serem transformados e de
recursos de transforma¸c˜ao comuns aos sistemas descritos.
2. Apresente dois exemplos de (i) atividades de programa¸c˜ao, (ii) atividades de carregando e (iii) atividades de sequenciamento
na opera¸c˜ao de qualquer um dos sistemas descritos. Justifique.
3. Quais s˜ao as vantagens e desvantagens dos dois diferentes m´etodos de programa¸c˜ao de filmes nas salas? Como cada
abordagem afeta os diferentes tipos de consumidor?
4. Quais s˜ao as principais diferen¸cas entre os dois cinemas, da perspectiva dos gerentes de opera¸c˜ao?